version: 2

sources:
  - name: lc
    schema: dbt_ahoang
    tables:
      - name: lc262_trips
      - name: lc262_users

models:
  - name: stg__trips
    description: "Cleaned trips from dbt.lc262_trips"
    columns:
      - name: id
        description: "The primary key for this trips table"
        tests: [not_null, unique]
  - name: stg__users
    description: "Cleaned users from dbt.lc262_users"
    columns:
      - name: users_id
        description: "The primary key for this users table"
        tests: [not_null, unique]
  - name: int__daily_trips
    description: "Daily Trips"
    columns:
      - name: request_at
        tests: [not_null]
      - name: city_id
        tests: [not_null]
  - name: int__trips_by_client
    columns:
      - name: request_at
        tests: [not_null]
      - name: client_id
        tests: [not_null, unique]
